apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: airflow-dags-syncer-deployment
spec:
  selector:
    matchLabels:
      app: dags-sync
  replicas: 1 
  template:
    metadata:
      labels:
        app: dags-sync
    spec:
      containers:
      - name: dags-sync
        image: 771502366784.dkr.ecr.us-west-2.amazonaws.com/wotc-airflow-dags:latest
        #command: ["python"]
        #args: ["run.py"]
        env:
        - name: AWS_ACCOUNT_ID
          valueFrom:
            configMapKeyRef:
              name: airflow-dags-syncer-config
              key: AWS_ACCOUNT_ID
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: airflow-dags-syncer-config
              key: AWS_REGION
        - name: AWS_CODECOMMIT_URL
          valueFrom:
            configMapKeyRef:
              name: airflow-dags-syncer-config
              key: AWS_CODECOMMIT_URL
        - name: SQS_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: airflow-dags-syncer-config
              key: SQS_QUEUE_NAME
        - name: GIT_REPO_URL
          valueFrom:
            configMapKeyRef:
              name: airflow-dags-syncer-config
              key: GIT_REPO_URL
        - name: GIT_REPO_DIR
          valueFrom:
            configMapKeyRef:
              name: airflow-dags-syncer-config
              key: GIT_REPO_DIR
        - name: GIT_PULL_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: airflow-dags-syncer-config
              key: GIT_PULL_INTERVAL
        - name: DAGS_DIR
          valueFrom:
            configMapKeyRef:
              name: airflow-dags-syncer-config
              key: DAGS_DIR

        volumeMounts:
        - name: airflow-dags
          mountPath: /usr/local/airflow/dags
        - name: airflow-dags-syncer-secrets
          mountPath: /root/.aws/credentials
          subPath: credentials
          readOnly: true
        - name: aws-config
          mountPath: /root/.aws/config
          subPath: config
        - name: gitconfig
          mountPath: /root/.gitconfig
          subPath: .gitconfig

      volumes:
      - name: airflow-dags
        persistentVolumeClaim:
          claimName: xtof-pv-test-3
      - name: airflow-dags-syncer-secrets
        secret:
          secretName: airflow-dags-syncer-secrets
      - name: aws-config
        configMap:
          name: airflow-dags-syncer-config
          items:
          - key: config
            path: config
      - name: gitconfig
        configMap:
          name: airflow-dags-syncer-config
          items:
          - key: .gitconfig
            path: .gitconfig
