apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "airflow-dags-syncer.fullname" . }}-config
  labels:
    app: {{ template "airflow-dags-syncer.name" . }}
    chart: {{ template "airflow-dags-syncer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.config.env }}
data:
{{ toYaml . | indent 2 }}
{{- end }}
